services:
  - type: web
    name: sentiment-api
    env: python
    region: oregon  # Puedes cambiar a: oregon, frankfurt, singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PORT
        generateValue: true